app = 'y-sweet'
primary_region = 'sjc'

kill_signal = "SIGTERM"
kill_timeout = 5

[build]

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
