app = 'y-sweet-staging'
primary_region = 'lax'

kill_signal = "SIGTERM"
kill_timeout = "5m0s"

[build]
  dockerfile = "Dockerfile" 

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = "connections"
    soft_limit = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
