# relay.toml - Relay Server Configuration File
# This file provides defaults that can be overridden by environment variables

[server]
# Server binding configuration
host = "0.0.0.0"              # RELAY_SERVER_HOST
port = 8080                   # PORT
metrics_port = 9090           # METRICS_PORT

# URL configuration
url_prefix = "https://api.example.com"  # RELAY_SERVER_URL

# Allowed hosts for context-aware URL generation
allowed_hosts = [
    { host = "api.example.com", scheme = "https" },
    { host = "localhost:8080", scheme = "http" },
    { host = "app.flycast", scheme = "http" }
]

# Checkpoint frequency in seconds
checkpoint_freq_seconds = 60  # RELAY_SERVER_CHECKPOINT_FREQ_SECONDS

# Document garbage collection
doc_gc = true                 # RELAY_SERVER_DOC_GC

# Error redaction in responses
redact_errors = false         # RELAY_SERVER_REDACT_ERRORS

[auth]
# Authentication configuration
enabled = false
# Private key for token signing (base64 encoded)
# Can be overridden by RELAY_SERVER_AUTH
# private_key = "base64_encoded_key_here"
# key_id = "prod-key-2024"     # RELAY_SERVER_KEY_ID

# Token defaults
default_expiration_seconds = 3600  # RELAY_SERVER_DEFAULT_EXPIRATION_SECONDS

[store]
# Storage backend configuration
# Type can be: "filesystem", "s3", "aws", "cloudflare", "backblaze", "minio", "tigris", "memory"
type = "memory"               # RELAY_SERVER_STORAGE (as s3://bucket/prefix)

# ==== Generic S3 Configuration (for custom S3-compatible services) ====
# [store]
# type = "s3"
# bucket = "relay-docs"
# region = "us-east-1"
# endpoint = ""                 # AWS_ENDPOINT_URL_S3 (for S3-compatible services)
# path_style = false            # AWS_S3_USE_PATH_STYLE
# presigned_url_expiration = 3600  # RELAY_SERVER_S3_PRESIGNED_URL_EXPIRATION
# prefix = ""
# access_key_id = "AKIA..."
# secret_access_key = "secret..."

# ==== AWS S3 ====
# [store]
# type = "aws"
# bucket = "my-bucket"
# region = "us-east-1"         # Optional, defaults to "us-east-1"
# access_key_id = "AKIA..."
# secret_access_key = "secret..."
# prefix = ""                  # Optional path prefix within bucket

# ==== Cloudflare R2 ====
# [store]
# type = "cloudflare"
# bucket = "my-bucket"
# account_id = "abc123..."
# access_key_id = "token_value"
# secret_access_key = "token_secret"
# prefix = ""                  # Optional path prefix within bucket

# ==== Backblaze B2 ====
# [store]
# type = "backblaze"
# bucket = "my-bucket"
# key_id = "key_id_here"
# application_key = "app_key_here"
# prefix = ""                  # Optional path prefix within bucket

# ==== MinIO ====
# [store]
# type = "minio"
# bucket = "my-bucket"
# endpoint = "https://minio.example.com:9000"
# access_key = "minioadmin"
# secret_key = "minioadmin"
# prefix = ""                  # Optional path prefix within bucket

# ==== Tigris ====
# [store]
# type = "tigris"
# bucket = "my-bucket"
# access_key_id = "token_value"
# secret_access_key = "token_secret"
# prefix = ""                  # Optional path prefix within bucket

# ==== Filesystem Storage ====
# [store]
# type = "filesystem"
# path = "/var/lib/relay/data"  # RELAY_SERVER_STORAGE (as filesystem path)

# [[webhooks]]
# # Webhook configuration (can have multiple)
# # Can be overridden by RELAY_SERVER_WEBHOOK_CONFIG (as JSON array)
# url = "https://webhook.example.com/relay"
# auth_token = "Bearer webhook_secret_123"
# prefix = "org-123-"           # Optional: only send events for docs with this prefix
# timeout_ms = 5000             # Optional: request timeout

[logging]
# Logging configuration
level = "info"                # RUST_LOG
format = "pretty"             # RELAY_SERVER_LOG_FORMAT: "json" or "pretty"